# Generated by Django 6.0.3 on 2026-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='repeat',
            field=models.PositiveIntegerField(blank=True, help_text='Repeat the task every X days', null=True),
        ),
    ]
