# Generated by Django 6.0.3 on 2026-04-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='completed',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('pruning', 'Pruning')], default='watering', max_length=50),
        ),
        migrations.CreateModel(
            name='ReminderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_date', models.DateField()),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reminders.reminder')),
            ],
            options={
                'db_table': 'reminder_history',
            },
        ),
    ]
